version: '3'

env:
  PROG: moneta
  BINDIR: ./bin
  SRCDIR: ./cmd/cli

tasks:
  default:
    deps: [build]

  build:
    sources:
      - ./**/*.go
    generates:
      - $BINDIR/$PROG
    cmds:
      - go build -o $BINDIR/$PROG $SRCDIR

  run:
    deps: [build]
    cmds:
      - $BINDIR/$PROG {{.CLI_ARGS}}

  clean:
    cmds:
      - rm -f $BINDIR/$PROG
      - rmdir $BINDIR
